make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C ./tests/pkg_fatfs_vfs test
r
ssh -t rici@saclay.iot-lab.info 'socat - tcp:nrf52dk-10.saclay.iot-lab.info:20000'
[auto_init_storage] error initializing sdcard_spi #0
Help: Press s to start test, r to print it is ready
[auto_init_storage] error initializing sdcard_spi #0
Help: Press s to start test, r to print it is ready
READY
s
START
main(): This is RIOT! (Version: 2020.07)
Tests for FatFs over VFS - test results will be printed in the format test_name:result
test_mount__mount:[FAILED]
test_
Traceback (most recent call last):
  File "/home/runner/work/RIOT/RIOT/tests/pkg_fatfs_vfs/tests/01-run.py", line 34, in <module>
    sys.exit(run(testfunc))
  File "/home/runner/work/RIOT/RIOT/dist/pythonlibs/testrunner/__init__.py", line 30, in run
    testfunc(child)
  File "/home/runner/work/RIOT/RIOT/tests/pkg_fatfs_vfs/tests/01-run.py", line 28, in testfunc
    raise TestFailed(child.after.split(':', 1)[0] + " test failed!")
__main__.TestFailed: test_mount__mount test failed!
/home/runner/work/RIOT/RIOT/tests/pkg_fatfs_vfs/../../Makefile.include:770: recipe for target 'test' failed
make: *** [test] Error 1

Return value: 2
